# Setup
title:        Wonnayoung's Home
tagline:      A responsive theme for your project on GitHub Pages
baseurl:      "http://wonnayoung.github.io"
paginate:     1

# About/contact
author:
  name:       Wonnayoung
  url:        http://wonnayoung.github.io

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
